### ISSUE TITLE
Exception caused when trying to evaluate regex segment condition against non string trait

### ISSUE THREAD

**Issue by matthewelwell** [Flagsmith/flagsmith-engine#156]
From logs: 

```
2023-03-15 16:53:39.984 : [ERROR] TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/var/task/src/utils/response.py", line 91, in handler_with_options
    return handler(event, context)
  File "/var/task/src/handlers.py", line 70, in identities
    response = identity_service.get_identify_with_traits_response(**kwargs)
  File "/var/task/src/identity.py", line 139, in get_identify_with_traits_response
    feature_state_models = self._get_identity_feature_states(
  File "/var/task/src/identity.py", line 323, in _get_identity_feature_states
    flags = get_identity_feature_states(
  File "/var/task/flag_engine/engine.py", line 53, in get_identity_feature_states
    _get_identity_feature_states_dict(
  File "/var/task/flag_engine/engine.py", line 101, in _get_identity_feature_states_dict
    identity_segments = get_identity_segments(environment, identity, override_traits)
  File "/var/task/flag_engine/segments/evaluator.py", line 17, in get_identity_segments
    return list(
  File "/var/task/flag_engine/segments/evaluator.py", line 19, in <lambda>
    lambda s: evaluate_identity_in_segment(identity, s, override_traits),
  File "/var/task/flag_engine/segments/evaluator.py", line 39, in evaluate_identity_in_segment
    return len(segment.rules) > 0 and all(
  File "/var/task/flag_engine/segments/evaluator.py", line 40, in <genexpr>
    _traits_match_segment_rule(
  File "/var/task/flag_engine/segments/evaluator.py", line 69, in _traits_match_segment_rule
    return matches_conditions and all(
  File "/var/task/flag_engine/segments/evaluator.py", line 70, in <genexpr>
    _traits_match_segment_rule(identity_traits, rule, segment_id, identity_id)
  File "/var/task/flag_engine/segments/evaluator.py", line 58, in _traits_match_segment_rule
    [
  File "/var/task/flag_engine/segments/evaluator.py", line 59, in <listcomp>
    _traits_match_segment_condition(
  File "/var/task/flag_engine/segments/evaluator.py", line 98, in _traits_match_segment_condition
    return condition.matches_trait_value(trait.trait_value) if trait else False
  File "/var/task/flag_engine/segments/models.py", line 36, in matches_trait_value
    return evaluator_function(trait_value)
  File "/var/task/flag_engine/segments/models.py", line 59, in evaluate_regex
    return re.compile(str(self.value)).match(trait_value) is not None
```

**Comment by khvn26** [comment]
Fixed.
